### ISSUE TITLE
[New Component Proposal]: 

### ISSUE THREAD

**Issue by Nisarg155** [developer-student-clubs/qUIck-react#5]
### 🧩 New Component Name

TextFields 

### 📝 Component Description

There can be  text fields multiple options 

1) without label
2) with Label 
3) with required 
4) text field with error messages 

### 🎯 Motivation

It will allow user to use clean and reusable text fields instead  instead of creating it from scratch

### I agree to and respect the Code of Conduct

- [X] I will follow [CONTRIBUTING GUIDELINES](../blob/main/.github/CONTRIBUTING_GUIDELINE.md)

**Comment by Kris0011** [comment]
assigned @Nisarg155
