### ISSUE TITLE
[New Component Proposal]: 

### ISSUE THREAD

**Issue by Nisarg155** [developer-student-clubs/qUIck-react#8]
### 🧩 New Component Name

carousel slider 

### 📝 Component Description

1. **Image Galleries**: Display multiple product images or showcase a collection of photographs.

**Key Features**:
- **Auto-Play**: Ability to set the carousel to auto-play, cycling through content items at predefined intervals.
- **Manual Navigation**: Navigation controls (next/previous) and clickable dots for manual content navigation.
- **Responsive Design**: Adaptation to different screen sizes and orientations for a seamless user experience.
- **Customization**: Options to adjust transition effects, timing, size, and appearance to match our website's design.
- **Infinite Loop**: Support for an infinite loop where the carousel continuously cycles from the last item back to the first.
- **Transitions**: Customizable transition effects, such as sliding, fading, or other animations.

### 🎯 Motivation

**Visually Engaging Content**: A carousel slider is an interactive and visually engaging component that enables us to dynamically showcase multiple content items. It provides an appealing way to draw the user's attention to key messages, products, or features.

### I agree to and respect the Code of Conduct

- [X] I will follow [CONTRIBUTING GUIDELINES](../blob/main/.github/CONTRIBUTING_GUIDELINE.md)

**Comment by Kris0011** [comment]
Assigned to @Nisarg155
